stages:
  - build
  #- test
  - deploy

variables:
  # 线上版本-构建路径
  BUILD_ONLINE_PATH: /disk2/gitlab-ci/build/online/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  # 线上版本-部署的主机地址,','号分隔
  DEPLOY_ONLINE_SERVER_HOSTS: 10.10.10.100

  # 测试版本-构建路径
  BUILD_TESTING_PATH: /disk2/gitlab-ci/build/testing/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  # 测试版本-部署的主机地址,','号分隔 (汉子科技测试机器内容IP:10.10.10.100,外网:dev1.server.han-zi.cn)
  DEPLOY_TESTING_SERVER_HOSTS: 10.10.10.100

  # runner的部署脚本路径(通常不需要改)
  DEPLOY_SHELL_FILE: /home/gitlab-runner/runner-shell/deploy.sh

### 测试环境配置

# 构建测试环境
build-develop:
  stage: build
  tags:
    - hanzi-deploy

  only:
    - testing

  script:
    - rm -rf $BUILD_TESTING_PATH
    - mkdir -p $BUILD_TESTING_PATH
    - cp -r ./. $BUILD_TESTING_PATH
    - cd $BUILD_TESTING_PATH
    - npm install --registry=https://registry.npm.taobao.org
    - echo -E "$DEVELOP_CONFIG" | tr -d "\r" > .config.js
    - node --max-old-space-size=4096 build/build.js

  environment: testing

# 部署测试环境
deploy-develop:
  stage: deploy
  tags:
    - hanzi-deploy

  only:
    - testing

  variables:
    # 服务器代码地址
    SERVER_PATH: /disk2/gitlab-ci/project/testing/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_PIPELINE_ID
    # web服务指向目录
    SERVER_WEBROOT: /disk2/www/$CI_PROJECT_NAMESPACE/testing/$CI_PROJECT_NAME
  script:
    - cd $BUILD_TESTING_PATH
    - rm -rf .git
    - zip -r -q build.zip dist
    # 调用部署脚本
    - $DEPLOY_SHELL_FILE $DEPLOY_TESTING_SERVER_HOSTS $BUILD_TESTING_PATH/build.zip $SERVER_PATH $SERVER_WEBROOT 0

  after_script:
    # 删除临时代码
    - rm -rf $BUILD_TESTING_PATH

  environment: testing

### 正式线上环境配置

# 构建线上环境
build-online:
  stage: build
  tags:
    - hanzi-deploy

  only:
    - release

  script:
    - rm -rf $BUILD_ONLINE_PATH
    - mkdir -p $BUILD_ONLINE_PATH
    - cp -r ./. $BUILD_ONLINE_PATH
    - cd $BUILD_ONLINE_PATH
    - npm install --registry=https://registry.npm.taobao.org
    - echo -E "$ONLINE_CONFIG" | tr -d "\r" > .config.js
    - node --max-old-space-size=4096 build/build.js

  environment: online

deploy-online:
  stage: deploy
  tags:
    - hanzi-deploy

  only:
    - release

  variables:
    # 服务器代码地址
    SERVER_PATH: /disk2/gitlab-ci/project/online/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_PIPELINE_ID
    # web服务指向目录
    SERVER_WEBROOT: /disk2/www/$CI_PROJECT_NAMESPACE/online/$CI_PROJECT_NAME
  script:
    - cd $BUILD_ONLINE_PATH
    - rm -rf .git
    - zip -r -q build.zip dist
    # 调用部署脚本
    - $DEPLOY_SHELL_FILE $DEPLOY_ONLINE_SERVER_HOSTS $BUILD_ONLINE_PATH/build.zip $SERVER_PATH $SERVER_WEBROOT 0

  after_script:
    # 删除临时代码
    - rm -rf $BUILD_ONLINE_PATH

  environment: online